name: sarek-2.3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - asn1crypto=0.24.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - bcftools=1.8
  - bioconductor-biobase=2.40.0
  - bioconductor-biocgenerics=0.26.0
  - bioconductor-biocparallel=1.14.2
  - bioconductor-biostrings=2.48.0
  - bioconductor-delayedarray=0.6.6
  - bioconductor-genomeinfodb=1.16.0
  - bioconductor-genomeinfodbdata=1.1.0
  - bioconductor-genomicalignments=1.16.0
  - bioconductor-genomicranges=1.32.7
  - bioconductor-iranges=2.14.12
  - bioconductor-noiseq=2.24.0
  - bioconductor-rsamtools=1.32.3
  - bioconductor-rtracklayer=1.40.6
  - bioconductor-s4vectors=0.18.3
  - bioconductor-summarizedexperiment=1.10.1
  - bioconductor-xvector=0.20.0
  - bioconductor-zlibbioc=1.26.0
  - blas=1.0
  - bwa=0.7.17
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - cairo=1.14.10
  - certifi=2018.11.29
  - cffi=1.12.2
  - chardet=3.0.4
  - click=7.0
  - clustalw=2.1
  - colormath=3.0.0
  - cryptography=2.5
  - curl=7.64.0
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.2
  - ensembl-vep=95.1
  - enum34=1.1.6
  - expat=2.2.5
  - fastqc=0.11.8
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.12.6
  - freebayes=1.2.0
  - freetype=2.8.1
  - functools32=3.2.3.2
  - future=0.17.1
  - futures=3.2.0
  - gatk4=4.0.9.0
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.55.0
  - graphite2=1.3.13
  - graphviz=2.38.0
  - gsl=2.1
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - harfbuzz=1.7.6
  - htslib=1.9
  - icu=58.2
  - idna=2.8
  - igvtools=2.3.93
  - intel-openmp=2019.1
  - ipaddress=1.0.22
  - jinja2=2.10
  - jpeg=9c
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - libcurl=7.64.0
  - libdb=6.1.26
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=7.3.0
  - libgd=2.2.5
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.34
  - libssh2=1.8.0
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.9
  - libtool=2.4.6
  - libwebp=0.5.2
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lzstring=1.0.3
  - manta=1.4.0
  - markdown=2.6.11
  - markupsafe=1.1.1
  - matplotlib=2.2.2
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - multiqc=1.6
  - mysql-connector-c=6.1.11
  - ncurses=5.9
  - networkx=2.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openjdk=8.0.192
  - openssl=1.0.2r
  - paml=4.9
  - pango=1.40.14
  - parallel=20190122
  - pcre=8.39
  - perl=5.26.2
  - perl-aceperl=1.92
  - perl-algorithm-diff=1.1903
  - perl-algorithm-munkres=0.08
  - perl-apache-test=1.40
  - perl-app-cpanminus=1.7044
  - perl-appconfig=1.71
  - perl-array-compare=3.0.1
  - perl-autoloader=5.74
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-db-hts=2.7
  - perl-bio-featureio=1.6.905
  - perl-bio-phylo=0.58
  - perl-bio-samtools=1.43
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.2
  - perl-bioperl-core=1.7.2
  - perl-bioperl-run=1.007002
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-cache-cache=1.08
  - perl-capture-tiny=0.48
  - perl-carp=1.38
  - perl-cgi=4.40
  - perl-class-data-inheritable=0.08
  - perl-class-inspector=1.32
  - perl-class-load=0.25
  - perl-class-load-xs=0.10
  - perl-class-method-modifiers=2.12
  - perl-clone=0.41
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.084
  - perl-compress-raw-zlib=2.084
  - perl-constant=1.33
  - perl-convert-binary-c=0.78
  - perl-convert-binhex=1.125
  - perl-crypt-rc4=2.02
  - perl-data-dumper=2.173
  - perl-data-optlist=0.110
  - perl-data-stag=0.14
  - perl-date-format=2.30
  - perl-db-file=1.843
  - perl-dbd-mysql=4.046
  - perl-dbd-sqlite=1.60
  - perl-dbi=1.642
  - perl-devel-globaldestruction=0.14
  - perl-devel-overloadinfo=0.005
  - perl-devel-stacktrace=2.03
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-digest-perl-md5=1.9
  - perl-digest-sha1=2.13
  - perl-dist-checkconflicts=0.11
  - perl-dynaloader=1.25
  - perl-email-date-format=1.005
  - perl-encode=2.88
  - perl-encode-locale=1.05
  - perl-error=0.17027
  - perl-eval-closure=0.14
  - perl-exception-class=1.44
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-cppguess=0.12
  - perl-extutils-makemaker=7.34
  - perl-file-listing=6.04
  - perl-file-path=2.15
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-temp=0.2304
  - perl-file-which=1.23
  - perl-font-afm=1.20
  - perl-font-ttf=1.06
  - perl-gd=2.70
  - perl-getopt-long=2.50
  - perl-graph=0.9704
  - perl-graphviz=2.24
  - perl-html-element-extended=1.18
  - perl-html-entities-numbered=0.04
  - perl-html-formatter=2.16
  - perl-html-parser=3.72
  - perl-html-tableextract=2.13
  - perl-html-tagset=3.20
  - perl-html-tidy=1.60
  - perl-html-tree=5.07
  - perl-html-treebuilder-xpath=0.14
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-image-info=1.38
  - perl-image-size=3.300
  - perl-importer=0.025
  - perl-io-compress=2.084
  - perl-io-html=1.001
  - perl-io-sessiondata=1.03
  - perl-io-socket-ssl=2.060
  - perl-io-string=1.08
  - perl-io-stringy=2.111
  - perl-io-tty=1.12
  - perl-ipc-run=20180523.0
  - perl-ipc-sharelite=0.17
  - perl-jcode=2.07
  - perl-json=4.00
  - perl-json-xs=2.34
  - perl-lib=0.63
  - perl-libwww-perl=6.36
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.02
  - perl-lwp-protocol-https=6.07
  - perl-lwp-simple=6.15
  - perl-mailtools=2.20
  - perl-math-cdf=0.1
  - perl-math-derivative=1.01
  - perl-math-random=0.72
  - perl-math-spline=0.02
  - perl-mime-base64=3.15
  - perl-mime-lite=3.030
  - perl-mime-tools=5.508
  - perl-mime-types=2.17
  - perl-mldbm=2.05
  - perl-module-implementation=0.09
  - perl-module-pluggable=5.2
  - perl-module-runtime=0.016
  - perl-module-runtime-conflicts=0.003
  - perl-moo=2.003004
  - perl-moose=2.2011
  - perl-mozilla-ca=20180117
  - perl-mro-compat=0.13
  - perl-net-http=6.18
  - perl-net-ssleay=1.85
  - perl-ntlm=1.09
  - perl-ole-storage_lite=0.19
  - perl-package-deprecationmanager=0.17
  - perl-package-stash=0.38
  - perl-package-stash-xs=0.28
  - perl-params-util=1.07
  - perl-parent=0.236
  - perl-parse-recdescent=1.967015
  - perl-pathtools=3.73
  - perl-pdf-api2=2.033
  - perl-perlio-gzip=0.20
  - perl-pod-escapes=1.07
  - perl-pod-usage=1.69
  - perl-postscript=0.06
  - perl-role-tiny=2.000006
  - perl-scalar-list-utils=1.45
  - perl-scope-guard=0.21
  - perl-sereal=4.005
  - perl-sereal-decoder=4.005
  - perl-sereal-encoder=4.005
  - perl-set-intervaltree=0.11
  - perl-set-scalar=1.29
  - perl-soap-lite=1.19
  - perl-socket=2.027
  - perl-sort-naturally=1.03
  - perl-spreadsheet-parseexcel=0.65
  - perl-spreadsheet-writeexcel=2.40
  - perl-statistics-descriptive=3.0702
  - perl-storable=3.11
  - perl-sub-exporter=0.987
  - perl-sub-exporter-progressive=0.001013
  - perl-sub-identify=0.12
  - perl-sub-info=0.002
  - perl-sub-install=0.928
  - perl-sub-name=0.21
  - perl-sub-quote=2.005001
  - perl-sub-uplevel=0.2800
  - perl-svg=2.84
  - perl-svg-graph=0.02
  - perl-task-weaken=1.06
  - perl-template-toolkit=2.26
  - perl-term-table=0.013
  - perl-test=1.26
  - perl-test-deep=1.128
  - perl-test-differences=0.64
  - perl-test-exception=0.43
  - perl-test-harness=3.42
  - perl-test-leaktrace=0.16
  - perl-test-more=1.001002
  - perl-test-most=0.35
  - perl-test-requiresinternet=0.05
  - perl-test-warn=0.36
  - perl-test2-suite=0.000117
  - perl-text-csv=1.99
  - perl-text-diff=1.45
  - perl-tie-ixhash=1.23
  - perl-time-hires=1.9758
  - perl-time-local=1.28
  - perl-timedate=2.30
  - perl-tree-dag_node=1.31
  - perl-try-tiny=0.30
  - perl-type-tiny=1.004004
  - perl-types-serialiser=1.0
  - perl-unicode-map=0.112
  - perl-uri=1.76
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-filter-buffertext=1.01
  - perl-xml-libxml=2.0132
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.00
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-sax-writer=0.57
  - perl-xml-simple=2.25
  - perl-xml-twig=3.52
  - perl-xml-writer=0.625
  - perl-xml-xpath=1.44
  - perl-xml-xpathengine=0.14
  - perl-xsloader=0.24
  - perl-yaml=1.27
  - pip=19.0.3
  - pixman=0.34.0
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pysocks=1.6.8
  - python=2.7.15
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyyaml=3.13
  - qt=5.6.2
  - qualimap=2.2.2b
  - r-base=3.4.1
  - r-bh=1.66.0_1
  - r-bitops=1.0_6
  - r-formatr=1.5
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.2
  - r-lambda.r=1.2.3
  - r-lattice=0.20_35
  - r-matrix=1.2_14
  - r-matrixstats=0.54.0
  - r-optparse=1.6.0
  - r-rcurl=1.95_4.11
  - r-snow=0.4_3
  - r-xml=3.98_1.16
  - readline=7.0
  - requests=2.21.0
  - samtools=1.8
  - setuptools=40.8.0
  - simplejson=3.16.1
  - singledispatch=3.4.0.3
  - sip=4.18.1
  - six=1.12.0
  - snpeff=4.3.1t
  - spectra=0.0.11
  - sqlite=3.20.1
  - strelka=2.9.3
  - subprocess32=3.5.3
  - t_coffee=11.0.8
  - tidyp=1.04
  - tk=8.6.9
  - tornado=5.1.1
  - unzip=6.0
  - urllib3=1.24.1
  - vcfanno=0.3.0
  - vcftools=0.1.16
  - wget=1.19.5
  - wheel=0.33.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
